baseURL = 'https://wingbeat.dummthings.dev/'
title = 'Wingbeat Documentation'
theme = 'hugo-book'

disablePathToLower = true
enableGitInfo = false

[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1

[params]
  BookTheme = 'auto'
  BookToC = true
  BookSection = 'docs'
  BookSearch = true
  BookComments = false
  BookLogo = 'img/logo.svg'
  BookLogoDark = 'img/logo-dark.svg'
  BookFavicon = 'img/logo.svg'
  BookFaviconDark = 'img/logo-dark.svg'
